### ISSUE TITLE
[BUG] 회원탈퇴한 유저의 떡국 전체 조회 간 EntityNotFoundException 

### ISSUE THREAD

**Issue by h-beeen** [tteokguk-please/tteokguk-api#65]
## Related PR & Issue Ticket Number
- 

## Describe your changes
-

## Next Step Todo

```bash
jakarta.persistence.EntityNotFoundException: Unable to find com.tteokguk.tteokguk.member.domain.Member with id 11
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$JpaEntityNotFoundDelegate.handleEntityNotFound(EntityManagerFactoryBuilderImpl.java:191) ~[hibernate-core-6.4.1.Final.jar:6.4.1.Final]
	at org.hibernate.proxy.AbstractLazyInitializer.checkTargetState(AbstractLazyInitializer.java:290) ~[hibernate-core-6.4.1.Final.jar:6.4.1.Final]
	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:176) ~[hibernate-core-6.4.1.Final.jar:6.4.1.Final]
	at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:314) ~[hibernate-core-6.4.1.Final.jar:6.4.1.Final]
	at org.hibernate.proxy.pojo.bytebuddy.ByteBuddyInterceptor.intercept(ByteBuddyInterceptor.java:44) ~[hibernate-core-6.4.1.Final.jar:6.4.1.Final]
	at org.hibernate.proxy.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:102) ~[hibernate-core-6.4.1.Final.jar:6.4.1.Final]
	at com.tteokguk.tteokguk.member.domain.Member$HibernateProxy$d9fNAzDB.getNickname(Unknown Source) ~[main/:na]
	at com.tteokguk.tteokguk.tteokguk.application.dto.response.assembler.TteokgukResponseAssembler.toTteokgukResponse(TteokgukResponseAssembler.java:25) ~[main/:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[na:na]
```

**Comment by h-beeen** [comment]
조회쿼리 조건 deleted = false로 슈팅
